-- MySQL Script generated by MySQL Workbench
-- Sun Apr 13 21:05:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE ecommerce;
USE ecommerce;

CREATE TABLE IF NOT EXISTS Fornecedor (
  idFornecedor INT NOT NULL AUTO_INCREMENT,
  razaoSocial VARCHAR(70) NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  contato VARCHAR(45) NOT NULL,
  PRIMARY KEY (idFornecedor),
  UNIQUE INDEX CNPJ_UNIQUE (CNPJ ASC) VISIBLE,
  UNIQUE INDEX razaoSocial_UNIQUE (razaoSocial ASC) VISIBLE,
  UNIQUE INDEX contato_UNIQUE (contato ASC) VISIBLE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Produto (
  idProduto INT NOT NULL AUTO_INCREMENT,
  categoria ENUM('Eletrônicos', 'Vestuário', 'Brinquedos', 'Alimentos', 'Móveis') NOT NULL,
  descricao VARCHAR(45) NULL,
  valor FLOAT NOT NULL,
  status ENUM('Disponível', 'Em falta') NOT NULL,
  avaliacao FLOAT NULL,
  PRIMARY KEY (idProduto)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Inventario (
  Fornecedor_idFornecedor INT NOT NULL,
  Produto_idProduto INT NOT NULL,
  PRIMARY KEY (Fornecedor_idFornecedor, Produto_idProduto),
  INDEX fk_Inventario_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  INDEX fk_Inventario_Fornecedor_idx (Fornecedor_idFornecedor ASC) VISIBLE,
  CONSTRAINT fk_Fornecedor_has_Produto_Fornecedor
    FOREIGN KEY (Fornecedor_idFornecedor)
    REFERENCES Fornecedor (idFornecedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Fornecedor_has_Produto_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS EstoqueProdutos (
  idEstoque INT NOT NULL AUTO_INCREMENT,
  local VARCHAR(45) NOT NULL,
  Produto_idProduto INT NOT NULL,
  quantidade INT NOT NULL,
  PRIMARY KEY (idEstoque, Produto_idProduto),
  INDEX fk_EstoqueProdutos_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  CONSTRAINT fk_EstoqueProdutos_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Vendedor (
  idVendedor INT NOT NULL AUTO_INCREMENT,
  razaoSocial VARCHAR(70) NOT NULL,
  nomeFantasia VARCHAR(45) NULL,
  local VARCHAR(45) NULL,
  contato VARCHAR(45) NOT NULL,
  PRIMARY KEY (idVendedor),
  UNIQUE INDEX razaoSocial_UNIQUE (razaoSocial ASC) VISIBLE,
  UNIQUE INDEX contato_UNIQUE (contato ASC) VISIBLE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Anuncio (
  Vendedor_idVendedor INT NOT NULL,
  Produto_idProduto INT NOT NULL,
  quantidade INT NOT NULL,
  PRIMARY KEY (Vendedor_idVendedor, Produto_idProduto),
  INDEX fk_Anuncio_Vendedor1_idx (Vendedor_idVendedor ASC) VISIBLE,
  INDEX fk_Anuncio_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  CONSTRAINT fk_Produto_has_Vendedor_Vendedor1
    FOREIGN KEY (Vendedor_idVendedor)
    REFERENCES Vendedor (idVendedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Anuncio_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Cliente (
  idCliente INT NOT NULL AUTO_INCREMENT,
  endereco VARCHAR(150) NULL,
  PRIMARY KEY (idCliente)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ClientePessoaFisica (
  Cliente_idCliente INT NOT NULL,
  cpf CHAR(11) NOT NULL,
  primeiroNome VARCHAR(15) NOT NULL,
  sobrenome VARCHAR(30) NOT NULL,
  dataNascimento DATE NULL,
  PRIMARY KEY (Cliente_idCliente, cpf),
  UNIQUE INDEX cpf_UNIQUE (cpf ASC) VISIBLE,
  CONSTRAINT fk_PessoaFisica_Cliente1
    FOREIGN KEY (Cliente_idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ClientePessoaJuridica (
  Cliente_idCliente INT NOT NULL,
  CNPJ CHAR(14) NOT NULL,
  razaoSocial VARCHAR(70) NOT NULL,
  nomeFantasia VARCHAR(45) NULL,
  PRIMARY KEY (Cliente_idCliente, CNPJ),
  UNIQUE INDEX razaoSocial_UNIQUE (razaoSocial ASC) VISIBLE,
  UNIQUE INDEX CNPJ_UNIQUE (CNPJ ASC) VISIBLE,
  CONSTRAINT fk_PessoaJuridica_Cliente1
    FOREIGN KEY (Cliente_idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Entrega (
  idEntrega INT NOT NULL AUTO_INCREMENT,
  valorFrete FLOAT NOT NULL,
  codigoRastreio VARCHAR(45) NULL,
  prazo DATE NULL,
  PRIMARY KEY (idEntrega),
  UNIQUE INDEX codigoRastreio_UNIQUE (codigoRastreio ASC) VISIBLE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pedido (
  idPedido INT NOT NULL AUTO_INCREMENT,
  status ENUM('Em aberto', 'Processando', 'Enviado', 'Entregue') NOT NULL DEFAULT 'Em aberto',
  descricao VARCHAR(45) NULL,
  Cliente_idCliente INT NOT NULL,
  Entrega_idEntrega INT NOT NULL,
  PRIMARY KEY (idPedido, Cliente_idCliente, Entrega_idEntrega),
  INDEX fk_Pedido_Cliente1_idx (Cliente_idCliente ASC) VISIBLE,
  INDEX fk_Pedido_Entrega1_idx (Entrega_idEntrega ASC) VISIBLE,
  CONSTRAINT fk_Pedido_Cliente1
    FOREIGN KEY (Cliente_idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Entrega1
    FOREIGN KEY (Entrega_idEntrega)
    REFERENCES Entrega (idEntrega)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Item (
  Pedido_idPedido INT NOT NULL,
  Produto_idProduto INT NOT NULL,
  quantidade INT NOT NULL,
  PRIMARY KEY (Pedido_idPedido, Produto_idProduto),
  INDEX fk_Item_Produto1_idx (Produto_idProduto ASC) VISIBLE,
  INDEX fk_Item_Pedido1_idx (Pedido_idPedido ASC) VISIBLE,
  CONSTRAINT fk_Pedido_has_Produto_Pedido1
    FOREIGN KEY (Pedido_idPedido)
    REFERENCES Pedido (idPedido)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_has_Produto_Produto1
    FOREIGN KEY (Produto_idProduto)
    REFERENCES Produto (idProduto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS FormaPagamento (
  idFormaPagamento INT NOT NULL AUTO_INCREMENT,
  tipoPagamento ENUM('Boleto', 'Crédito', 'Débito', 'PIX', 'Carteira Digital') NOT NULL,
  codigoIdentificador VARCHAR(200) NOT NULL COMMENT 'Còdigos do cartão, código de barras ou PIX Copia e Cola.',
  PRIMARY KEY (idFormaPagamento)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pagamento (
  Pedido_Cliente_idCliente INT NOT NULL,
  Pedido_idPedido INT NOT NULL,
  FormaPagamento_idFormaPagamento INT NOT NULL,
  PRIMARY KEY (Pedido_Cliente_idCliente, Pedido_idPedido, FormaPagamento_idFormaPagamento),
  INDEX fk_Pagamento_FormaPagamento1_idx (FormaPagamento_idFormaPagamento ASC) VISIBLE,
  INDEX fk_Pagamento_Pedido1_idx (Pedido_idPedido ASC, Pedido_Cliente_idCliente ASC) VISIBLE,
  CONSTRAINT fk_FormaPagamento_has_Cliente_FormaPagamento1
    FOREIGN KEY (FormaPagamento_idFormaPagamento)
    REFERENCES FormaPagamento (idFormaPagamento)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Possui_Pedido1
    FOREIGN KEY (Pedido_idPedido, Pedido_Cliente_idCliente)
    REFERENCES Pedido (idPedido, Cliente_idCliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- Inserções para Fornecedor
INSERT INTO Fornecedor VALUES (1, 'Tech Solutions LTDA', '12345678000101', 'contato@techsolutions.com');
INSERT INTO Fornecedor VALUES (2, 'Comercial Oliveira ME', '23456789000102', 'vendas@oliveiracomercial.com');
INSERT INTO Fornecedor VALUES (3, 'Distribuidora Alfa SA', '34567890000103', 'atendimento@alfadistribuidora.com');
INSERT INTO Fornecedor VALUES (4, 'Global Importações EIRELI', '45678900000104', 'importacoes@global.com');
INSERT INTO Fornecedor VALUES (5, 'Super Fornecimentos Ltda', '56789000000105', 'suporte@superfornecimentos.com');
INSERT INTO Fornecedor VALUES (6, 'EcoLog Distribuição', '67890000000106', 'contato@ecolog.com.br');
INSERT INTO Fornecedor VALUES (7, 'Fornecedora Nobre S/A', '78900000000107', 'nobre@fornecedores.com');

-- Inserções para Produto
INSERT INTO Produto VALUES (1, 'Eletrônicos', 'Smartphone X200', 2499.99, 'Disponível', 4.5);
INSERT INTO Produto VALUES (2, 'Vestuário', 'Jaqueta Jeans', 199.90, 'Disponível', 4.2);
INSERT INTO Produto VALUES (3, 'Brinquedos', 'Blocos de Montar', 89.99, 'Disponível', 4.8);
INSERT INTO Produto VALUES (4, 'Alimentos', 'Caixa de Chocolates', 34.50, 'Em falta', 4.7);
INSERT INTO Produto VALUES (5, 'Móveis', 'Cadeira de Escritório', 459.00, 'Disponível', 4.3);
INSERT INTO Produto VALUES (6, 'Eletrônicos', 'Fone de Ouvido Bluetooth', 149.90, 'Disponível', 4.6);
INSERT INTO Produto VALUES (7, 'Vestuário', 'Camiseta Estampada', 59.90, 'Em falta', 3.9);
INSERT INTO Produto VALUES (8, 'Brinquedos', 'Carrinho de Controle Remoto', 129.99, 'Disponível', 4.1);
INSERT INTO Produto VALUES (9, 'Alimentos', 'Pacote de Biscoitos', 7.49, 'Disponível', 4.0);
INSERT INTO Produto VALUES (10, 'Móveis', 'Mesa de Jantar 6 lugares', 899.99, 'Em falta', 4.4);
INSERT INTO Produto VALUES (11, 'Eletrônicos', 'Notebook Gamer GX15', 5499.90, 'Disponível', 4.9);
INSERT INTO Produto VALUES (12, 'Vestuário', 'Calça Jeans Slim', 129.90, 'Disponível', 4.1);
INSERT INTO Produto VALUES (13, 'Brinquedos', 'Boneca Interativa', 119.99, 'Disponível', 4.6);
INSERT INTO Produto VALUES (14, 'Alimentos', 'Suco Natural 1L', 8.99, 'Disponível', 4.2);
INSERT INTO Produto VALUES (15, 'Móveis', 'Estante de Livros', 299.00, 'Disponível', 4.3);
INSERT INTO Produto VALUES (16, 'Eletrônicos', 'Smartwatch Fit', 379.90, 'Disponível', 4.7);

-- Inserções para Inventario
INSERT INTO Inventario VALUES (1, 1);
INSERT INTO Inventario VALUES (1, 2);
INSERT INTO Inventario VALUES (2, 3);
INSERT INTO Inventario VALUES (2, 4);
INSERT INTO Inventario VALUES (3, 5);
INSERT INTO Inventario VALUES (3, 6);
INSERT INTO Inventario VALUES (4, 7);
INSERT INTO Inventario VALUES (4, 8);
INSERT INTO Inventario VALUES (5, 9);
INSERT INTO Inventario VALUES (5, 10);
INSERT INTO Inventario VALUES (6, 11);
INSERT INTO Inventario VALUES (6, 12);
INSERT INTO Inventario VALUES (7, 13);
INSERT INTO Inventario VALUES (7, 14);
INSERT INTO Inventario VALUES (1, 15);
INSERT INTO Inventario VALUES (2, 16);

-- Inserções para EstoqueProdutos
INSERT INTO EstoqueProdutos VALUES (1, 'Centro SP', 1, 150);
INSERT INTO EstoqueProdutos VALUES (2, 'Zona Norte SP', 2, 80);
INSERT INTO EstoqueProdutos VALUES (3, 'Centro SP', 3, 120);
INSERT INTO EstoqueProdutos VALUES (4, 'Filial RJ', 4, 60);
INSERT INTO EstoqueProdutos VALUES (5, 'Filial MG', 5, 200);
INSERT INTO EstoqueProdutos VALUES (6, 'Centro SP', 6, 100);
INSERT INTO EstoqueProdutos VALUES (7, 'Filial PR', 7, 45);
INSERT INTO EstoqueProdutos VALUES (8, 'Filial RS', 8, 30);
INSERT INTO EstoqueProdutos VALUES (9, 'Centro SP', 9, 75);
INSERT INTO EstoqueProdutos VALUES (10, 'Zona Norte SP', 10, 55);
INSERT INTO EstoqueProdutos VALUES (11, 'Centro SP', 11, 25);
INSERT INTO EstoqueProdutos VALUES (12, 'Filial RJ', 12, 140);
INSERT INTO EstoqueProdutos VALUES (13, 'Filial MG', 13, 90);
INSERT INTO EstoqueProdutos VALUES (14, 'Filial PR', 14, 35);
INSERT INTO EstoqueProdutos VALUES (15, 'Filial RS', 15, 100);
INSERT INTO EstoqueProdutos VALUES (16, 'Centro SP', 16, 85);
INSERT INTO EstoqueProdutos VALUES (17, 'Filial RJ', 1, 40);
INSERT INTO EstoqueProdutos VALUES (18, 'Filial MG', 5, 70);
INSERT INTO EstoqueProdutos VALUES (19, 'Zona Norte SP', 9, 20);
INSERT INTO EstoqueProdutos VALUES (20, 'Filial RS', 13, 50);

-- Inserções para Vendedor
INSERT INTO Vendedor VALUES (1, 'Loja Tech Online LTDA', 'TechOnline', 'São Paulo - SP', 'contato@techonline.com');
INSERT INTO Vendedor VALUES (2, 'Vestuário Fashion ME', 'FashionLook', 'Rio de Janeiro - RJ', 'vendas@fashionlook.com');
INSERT INTO Vendedor VALUES (3, 'Brinquedos Alegria SA', 'Alegria Kids', 'Belo Horizonte - MG', 'suporte@alegriakids.com');
INSERT INTO Vendedor VALUES (4, 'Alimentos Saudáveis Ltda', 'NutriVida', 'Curitiba - PR', 'nutrivida@saudaveis.com');
INSERT INTO Vendedor VALUES (5, 'Móveis Planejados EIRELI', 'DesignLar', 'Porto Alegre - RS', 'atendimento@designlar.com');
INSERT INTO Vendedor VALUES (6, 'Eletrônicos Express LTDA', 'EletroX', 'Fortaleza - CE', 'contato@eletrox.com');
INSERT INTO Vendedor VALUES (7, 'Moda Jovem Comércio ME', 'TrendYou', 'Recife - PE', 'trendyou@modajovem.com');
INSERT INTO Vendedor VALUES (8, 'Super Casa Importados', 'CasaMax', 'Salvador - BA', 'suporte@casamax.com');
INSERT INTO Vendedor VALUES (9, 'Tech Solutions Market', 'TechMarket', 'Brasília - DF', 'info@techmarket.com');
INSERT INTO Vendedor VALUES (10, 'Utilidades & Cia S/A', 'UtilCia', 'Manaus - AM', 'utilidades@ciasa.com');

-- Inserções para Anuncio
INSERT INTO Anuncio VALUES (1, 1, 50);
INSERT INTO Anuncio VALUES (2, 3, 30);
INSERT INTO Anuncio VALUES (3, 5, 40);
INSERT INTO Anuncio VALUES (4, 2, 25);
INSERT INTO Anuncio VALUES (5, 6, 15);
INSERT INTO Anuncio VALUES (6, 8, 20);
INSERT INTO Anuncio VALUES (7, 4, 35);
INSERT INTO Anuncio VALUES (8, 7, 18);
INSERT INTO Anuncio VALUES (9, 9, 60);
INSERT INTO Anuncio VALUES (10, 10, 22);

-- Inserções para Cliente
INSERT INTO Cliente VALUES (1, 'Endereço 1');
INSERT INTO Cliente VALUES (2, 'Endereço 2');
INSERT INTO Cliente VALUES (3, 'Endereço 3');
INSERT INTO Cliente VALUES (4, 'Endereço 4');
INSERT INTO Cliente VALUES (5, 'Endereço 5');
INSERT INTO Cliente VALUES (6, 'Endereço 6');
INSERT INTO Cliente VALUES (7, 'Endereço 7');
INSERT INTO Cliente VALUES (8, 'Endereço 8');
INSERT INTO Cliente VALUES (9, 'Endereço 9');
INSERT INTO Cliente VALUES (10, 'Endereço 10');

-- Inserções para ClientePessoaFisica
INSERT INTO ClientePessoaFisica VALUES (1, '12345678901', 'João', 'Silva', '1990-05-12');
INSERT INTO ClientePessoaFisica VALUES (2, '23456789012', 'Maria', 'Souza', '1985-03-22');
INSERT INTO ClientePessoaFisica VALUES (3, '34567890123', 'Carlos', 'Oliveira', '1978-11-30');
INSERT INTO ClientePessoaFisica VALUES (4, '45678901234', 'Ana', 'Costa', '1992-07-15');
INSERT INTO ClientePessoaFisica VALUES (5, '56789012345', 'Pedro', 'Santos', '1988-09-09');
INSERT INTO ClientePessoaFisica VALUES (6, '67890123456', 'Juliana', 'Almeida', '1995-01-25');
INSERT INTO ClientePessoaFisica VALUES (7, '78901234567', 'Lucas', 'Martins', '2000-04-10');
INSERT INTO ClientePessoaFisica VALUES (8, '89012345678', 'Fernanda', 'Ribeiro', '1993-12-01');

-- Inserções para ClientePessoaJuridica
INSERT INTO ClientePessoaJuridica VALUES (9, '11222333000199', 'Empresa XPTO LTDA', 'XPTO Soluções');
INSERT INTO ClientePessoaJuridica VALUES (10, '22333444000188', 'Comercial ABC S/A', 'ABC Distribuidora');

-- Inserções para Entrega
INSERT INTO Entrega VALUES (1, 25.90, 'RA123456789BR', '2025-04-20');
INSERT INTO Entrega VALUES (2, 15.50, 'RB987654321BR', '2025-04-18');
INSERT INTO Entrega VALUES (3, 32.75, 'RC456789123BR', '2025-04-22');
INSERT INTO Entrega VALUES (4, 20.00, 'RD654321987BR', '2025-04-19');
INSERT INTO Entrega VALUES (5, 18.30, 'RE321654987BR', '2025-04-21');
INSERT INTO Entrega VALUES (6, 27.45, 'RF789456123BR', '2025-04-23');
INSERT INTO Entrega VALUES (7, 22.10, 'RG159753486BR', '2025-04-25');

-- Inserções para Pedido
INSERT INTO Pedido VALUES (1, 'Em aberto', 'Pedido de eletrônicos', 1, 1);
INSERT INTO Pedido VALUES (2, 'Processando', 'Pedido de roupas', 2, 2);
INSERT INTO Pedido VALUES (3, 'Enviado', 'Pedido de brinquedos', 3, 3);
INSERT INTO Pedido VALUES (4, 'Entregue', 'Pedido de alimentos', 4, 4);
INSERT INTO Pedido VALUES (5, 'Processando', 'Pedido de móveis', 5, 5);
INSERT INTO Pedido VALUES (6, 'Em aberto', 'Pedido misto', 6, 6);
INSERT INTO Pedido VALUES (7, 'Enviado', 'Pedido com frete expresso', 7, 7);

-- Inserções para Item
INSERT INTO Item VALUES (1, 1, 2);
INSERT INTO Item VALUES (1, 2, 1);
INSERT INTO Item VALUES (1, 3, 5);

INSERT INTO Item VALUES (2, 4, 3);
INSERT INTO Item VALUES (2, 5, 2);
INSERT INTO Item VALUES (2, 6, 4);

INSERT INTO Item VALUES (3, 7, 1);
INSERT INTO Item VALUES (3, 8, 3);

INSERT INTO Item VALUES (4, 9, 6);
INSERT INTO Item VALUES (4, 10, 2);

INSERT INTO Item VALUES (5, 11, 2);
INSERT INTO Item VALUES (5, 12, 2);
INSERT INTO Item VALUES (5, 13, 1);

INSERT INTO Item VALUES (6, 14, 4);
INSERT INTO Item VALUES (6, 15, 3);

INSERT INTO Item VALUES (7, 16, 2);
INSERT INTO Item VALUES (7, 1, 1);
INSERT INTO Item VALUES (7, 5, 2);
INSERT INTO Item VALUES (7, 9, 1);
INSERT INTO Item VALUES (7, 11, 1);

-- Inserções para FormaPagamento
INSERT INTO FormaPagamento VALUES (1, 'Crédito', '4111111111111111');
INSERT INTO FormaPagamento VALUES (2, 'Débito', '5500000000000004');
INSERT INTO FormaPagamento VALUES (3, 'PIX', 'pix-copia-e-cola-123456789');
INSERT INTO FormaPagamento VALUES (4, 'Boleto', '34191750090000123456789012345678901234567000');
INSERT INTO FormaPagamento VALUES (5, 'Carteira Digital', 'wallet-user-abc123');
INSERT INTO FormaPagamento VALUES (6, 'Crédito', '4012888888881881');
INSERT INTO FormaPagamento VALUES (7, 'Débito', '30000000000004');

-- Inserções para Pagamento
INSERT INTO Pagamento VALUES (1, 1, 1);
INSERT INTO Pagamento VALUES (2, 2, 2);
INSERT INTO Pagamento VALUES (3, 3, 3);
INSERT INTO Pagamento VALUES (4, 4, 4);
INSERT INTO Pagamento VALUES (5, 5, 5);
INSERT INTO Pagamento VALUES (6, 6, 6);
INSERT INTO Pagamento VALUES (7, 7, 7);

